version: "3"
services:
  proxy:
    build: ./
    networks:
      - webservice-1
      - webservice-2
    ports:
      - "80:80"
    container_name: proxy

networks:
  webservice-1:
    external:
      name: webservice-1_default
  webservice-2:
    external:
      name: webservice-2_default
# networks:
#   webservice-1:
#     external: true
#       name: webservice-1
#   webservice-2:
#     external: true
#       name: webservice-2
